version: "3"

networks:
  nginx-php8-alpine:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - nginx-php8-alpine

  php:
    image: php:8.0-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8
    volumes:
    - ./:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - nginx-php8-alpine
